version: '3.4'

services:
  dashboard:
    image: ${DOCKER_REGISTRY-}dashboard
    build:
      context: .
      dockerfile: TrafficLightCheckinDashboard/Dockerfile
    ports:
      - 80:80
    networks:
      - network
  
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - network
    volumes:
      - '../data:/data/db'

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 81:80
    networks:
      network:
        aliases: 
          - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

networks:
  network:

